import { Language } from './types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  'pt-BR': {
    appTitle: 'Arquiteto de Masmorras do Urso',
    navGenerator: 'Gerador',
    navBuilder: 'Sistemas',
    navEditor: 'Gerenciador',
    navDatabase: 'Banco de Dados',
    navSettings: 'Configurações',
    
    // Generator
    genTitle: 'Gerador de Eventos',
    genSelectSystem: 'Sistemas Ativos (Selecione um ou mais)',
    genQuantity: 'Quantidade de Eventos',
    genSelectType: 'Tipo de Sala',
    genRandom: 'Aleatório',
    genButton: 'Gerar Evento',
    genNoSystem: 'Crie um sistema primeiro!',
    genNoEvents: 'Nenhum evento encontrado nos sistemas selecionados para este critério.',
    
    // Card
    cardDifficulty: 'Dificuldade',
    cardReward: 'Recompensa',
    cardSystem: 'Sistema',
    cardExport: 'Salvar Imagem',

    // Builder
    buildTitle: 'Construtor de Sistema',
    buildNameLabel: 'Nome do Sistema',
    buildStatsLabel: 'Estatísticas (separadas por vírgula)',
    buildSave: 'Salvar Sistema',
    buildList: 'Sistemas Existentes',
    buildDelete: 'Excluir',

    // Editor
    editTitle: 'Gerenciador de Eventos',
    editFilterSystem: 'Sistema',
    editFilterType: 'Tipo',
    editFilterDiff: 'Dificuldade',
    editAll: 'Todos',
    editNew: 'Novo Evento',
    editEdit: 'Editar',
    editDelete: 'Excluir',
    editSave: 'Salvar Alterações',
    editCancel: 'Cancelar',
    colType: 'Tipo',
    colDesc: 'Descrição',
    colDiff: 'Dificuldade',
    colReward: 'Recompensa',
    modalTitleAdd: 'Adicionar Novo Evento',
    modalTitleEdit: 'Editar Evento',

    // Database
    dbTitle: 'Importação e Exportação',
    dbStep1Title: 'Passo 1: Obter Modelo',
    dbStep1Desc: 'Baixe o arquivo Excel estruturado para preencher com seu conteúdo.',
    dbDownloadTemplate: 'Baixar Modelo (.xlsx)',
    dbStep2Title: 'Passo 2: Carregar Dados',
    dbStep2Desc: 'Importe seu arquivo Excel ou CSV preenchido.',
    dbUpload: 'Carregar Dados (.xlsx / .csv)',
    dbStats: 'Estatísticas do Banco',
    dbTotalEvents: 'Total de Eventos',
    dbClear: 'Limpar Tudo',
    
    // Settings
    setTitle: 'Configurações',
    setLanguage: 'Idioma',
    setTheme: 'Editor de Tema do Cartão',
    setBgColor: 'Cor de Fundo',
    setTextColor: 'Cor do Texto',
    setBorderColor: 'Cor da Borda',
    setAccentColor: 'Cor de Destaque',
  },
  'en': {
    appTitle: "Bear's Dungeon Architect",
    navGenerator: 'Generator',
    navBuilder: 'Systems',
    navEditor: 'Manager',
    navDatabase: 'Database',
    navSettings: 'Settings',

    genTitle: 'Event Generator',
    genSelectSystem: 'Active Systems (Select one or more)',
    genQuantity: 'Event Quantity',
    genSelectType: 'Room Type',
    genRandom: 'Random',
    genButton: 'Generate Event',
    genNoSystem: 'Create a system first!',
    genNoEvents: 'No events found in selected systems for this criteria.',

    cardDifficulty: 'Difficulty',
    cardReward: 'Reward',
    cardSystem: 'System',
    cardExport: 'Save Image',

    buildTitle: 'System Builder',
    buildNameLabel: 'System Name',
    buildStatsLabel: 'Stats (comma separated)',
    buildSave: 'Save System',
    buildList: 'Existing Systems',
    buildDelete: 'Delete',

    editTitle: 'Event Manager',
    editFilterSystem: 'System',
    editFilterType: 'Type',
    editFilterDiff: 'Difficulty',
    editAll: 'All',
    editNew: 'New Event',
    editEdit: 'Edit',
    editDelete: 'Delete',
    editSave: 'Save Changes',
    editCancel: 'Cancel',
    colType: 'Type',
    colDesc: 'Description',
    colDiff: 'Difficulty',
    colReward: 'Reward',
    modalTitleAdd: 'Add New Event',
    modalTitleEdit: 'Edit Event',

    dbTitle: 'Import & Export',
    dbStep1Title: 'Step 1: Get Template',
    dbStep1Desc: 'Download the structured Excel file to fill with your content.',
    dbDownloadTemplate: 'Download Template (.xlsx)',
    dbStep2Title: 'Step 2: Upload Data',
    dbStep2Desc: 'Import your populated Excel or CSV file.',
    dbUpload: 'Upload Data (.xlsx / .csv)',
    dbStats: 'Database Stats',
    dbTotalEvents: 'Total Events',
    dbClear: 'Clear All',

    setTitle: 'Settings',
    setLanguage: 'Language',
    setTheme: 'Card Theme Editor',
    setBgColor: 'Background Color',
    setTextColor: 'Text Color',
    setBorderColor: 'Border Color',
    setAccentColor: 'Accent Color',
  },
  'es': {
    appTitle: 'Arquitecto de Mazmorras del Oso',
    navGenerator: 'Generador',
    navBuilder: 'Sistemas',
    navEditor: 'Gestor',
    navDatabase: 'Base de Datos',
    navSettings: 'Ajustes',

    genTitle: 'Generador de Eventos',
    genSelectSystem: 'Sistemas Activos (Seleccione uno o más)',
    genQuantity: 'Cantidad de Eventos',
    genSelectType: 'Tipo de Sala',
    genRandom: 'Aleatorio',
    genButton: 'Generar Evento',
    genNoSystem: '¡Crea un sistema primero!',
    genNoEvents: 'No se encontraron eventos en los sistemas seleccionados.',

    cardDifficulty: 'Dificultad',
    cardReward: 'Recompensa',
    cardSystem: 'Sistema',
    cardExport: 'Guardar Imagen',

    buildTitle: 'Constructor de Sistemas',
    buildNameLabel: 'Nombre del Sistema',
    buildStatsLabel: 'Estadísticas (separadas por comas)',
    buildSave: 'Guardar Sistema',
    buildList: 'Sistemas Existentes',
    buildDelete: 'Eliminar',

    editTitle: 'Gestor de Eventos',
    editFilterSystem: 'Sistema',
    editFilterType: 'Tipo',
    editFilterDiff: 'Dificultad',
    editAll: 'Todos',
    editNew: 'Nuevo Evento',
    editEdit: 'Editar',
    editDelete: 'Eliminar',
    editSave: 'Guardar Cambios',
    editCancel: 'Cancelar',
    colType: 'Tipo',
    colDesc: 'Descripción',
    colDiff: 'Dificultad',
    colReward: 'Recompensa',
    modalTitleAdd: 'Añadir Nuevo Evento',
    modalTitleEdit: 'Editar Evento',

    dbTitle: 'Importación y Exportación',
    dbStep1Title: 'Paso 1: Obtener Plantilla',
    dbStep1Desc: 'Descarga el archivo Excel estructurado para llenar con tu contenido.',
    dbDownloadTemplate: 'Descargar Plantilla (.xlsx)',
    dbStep2Title: 'Paso 2: Subir Datos',
    dbStep2Desc: 'Importa tu archivo Excel o CSV poblado.',
    dbUpload: 'Subir Datos (.xlsx / .csv)',
    dbStats: 'Estadísticas',
    dbTotalEvents: 'Total de Eventos',
    dbClear: 'Borrar Todo',

    setTitle: 'Ajustes',
    setLanguage: 'Idioma',
    setTheme: 'Editor de Tema de Tarjeta',
    setBgColor: 'Color de Fondo',
    setTextColor: 'Color de Texto',
    setBorderColor: 'Color de Borde',
    setAccentColor: 'Color de Acento',
  }
};

export const EVENT_TYPES = ['Combate', 'Elite', 'Loja', 'Descanso', 'Evento', 'Armadilha', 'Tesouro'];